name = "proxy-rs"
main = "build/worker/shim.mjs"
compatibility_date = "2025-01-26"

[build]
command = "cargo install -q worker-build && worker-build --release"

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true



[vars]
USER_ID = "1cc19698-31e7-47ca-a29b-34b6b1ded557"
PROXY_IP = ""
DEFAULT_PAGE = "<html><head><title>啦啦啦</title></head><body><h1>Hello, world!</h1></body></html>"
